spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/ctexchange
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always
